resources:
  database:
    type: postgres
    options:
      storage: 10
      version: "13.4"
services:
  web:
    build: .
    command: "buffalo dev"
    port: 3000
    health: /
    resources:
      - database
