---
development:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@db:5432/team_manager_development?sslmode=disable"}}

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@db:5432/team_manager_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/team_manager_production?sslmode=disable"}}
