version: 2.1
orbs:
  convox: convox/orb@1.4.1
workflows:
  deploy:
    jobs:
      - deploy
jobs:
  deploy:
    executor: convox/cli
    steps:
      - checkout
      - convox/deploy:
          rack: company/dev-v2
          host: console-staging.convox.com
          app: team-manager
