version: '3.7'

services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: team_manager_development

  pgadmin:
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    depends_on:
      - db

  team-manager:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: "buffalo dev"
    volumes:
      - ..:/app/golang-interview-project-taynan-souza
    ports:
      - 3000:3000
